---
## This playbook installs and configures AD authentication on CentOS(6-7) and Ubuntu(16.04+) machines

- name: Install and configure AD authentication
  hosts: all  
  become: yes
  become_method: sudo
    
  tasks:
    - name: Set Linux Distribution and Version
      set_fact:
        dist: "{% if ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6' %}centos6{% elif ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' %}centos7{% elif ansible_distribution == 'Ubuntu' %}ubuntu{% else %}centos7{% endif %}"

    - name: Install ad_auth required tools (CentOS 7)
      yum: 
        name: libselinux-python,realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,ntpdate,ntp,python-pip,sudo
        state: present
      when: dist == "centos7"
      become: true

    - name: Install and enable EPEL (CentOS)
      yum: 
        name: epel-release
        state: present
      when: dist == "centos7" or dist == "centos6"
      become: true

    - name: Install adcli required tools (CentOS 6)
      yum: 
        name: libselinux-python,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,ntpdate,ntp,python-pip,sudo
        state: present
      when: dist == "centos6"
      become: true 

    - name: Install required tools (Ubuntu)
      apt:
        name: 
          - realmd
          - sssd
          - sssd-tools
          - policykit-1
          - libnss-sss
          - libpam-sss
          - krb5-user
          - adcli 
          - samba-common-bin
        state: present
        update_cache: yes
      when: dist == 'ubuntu'

    - name: Install pexpect using pip (All Distros)
      pip:
        name: pexpect

    - name: Enable SSSD using Authconfig (CentOS 6 and 7)
      command: authconfig --enablesssd --enablesssdauth --update
      when: ansible_distribution == 'CentOS'

    - name: Check if machine is bound (CentOS 7 and Ubuntu)
      shell: /bin/bash -c "realm list | grep sssd"
      register: realmd_bound
      changed_when: false
      ignore_errors: true
      when: dist == "centos7" or dist == "ubuntu"

    - name: Add Kerberos Conf from Template (CentOS)
      template:
        src: templates/kerberos/cent_krb5.conf
        dest: /etc/krb5.conf
      when: ansible_distribution == 'CentOS'

    - name: Add Kerberos Conf from Template (Ubuntu)
      template:
        src: templates/kerberos/ubuntu_krb5.conf
        dest: /etc/krb5.conf
      when: realmd_bound is failed and dist == "ubuntu"


    - name: Add Realm Conf from Template (CentOS 7 and Ubuntu)
      template:
        src: templates/realm/realmd_centos7.conf
        dest: /etc/realmd.conf
      when: (realmd_bound is failed and dist == "centos7")
       
    - name: Add Realm Conf from Template (CentOS 7 and Ubuntu)
      template:
        src: templates/realm/realmd_ubuntu20.conf
        dest: /etc/realmd.conf
      when: (realmd_bound is failed and dist == "ubuntu")

    - name: Allow password SSH for AD group - line 1 (All Distros)
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        line: "AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys"
        regexp: "^AuthorizedKeysCommand "

    - name: Allow password SSH for AD Group - line 2 (CentOS 6)
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        line: "AuthorizedKeysCommandRunAs root"
        regexp: "^AuthorizedKeysCommandRunAs "
      when: dist == "centos6"

    - name: Allow password SSH for AD group - line 2 (CentOS 7 and Ubuntu)
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        line: "AuthorizedKeysCommandUser root"
        insertafter: "^AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys"
      when: dist == "centos7" or dist == "ubuntu"

    - name: Add LinuxSSH to PAM access list (All Distros)
      lineinfile: 
        dest: /etc/security/access.conf 
        state: present
        line: "+ : ({{ linux_ad_user_group }}) : ALL"
        insertbefore: BOF

    - name: Add AD group to Sudoers file (All Distros)
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%{{ linux_admin_ad_user_group }} "
        line: "%{{ linux_admin_ad_user_group }}   ALL=(ALL)   ALL"

    - name: Make sure krb5.conf.d directory exists (All Distros)
      file:
        path: /etc/krb5.conf.d
        state: directory
        owner: root
        group: root
        mode: 0775

    - name: Join system to AD and put the computer object in the Linux Servers OU (CentOS 7)
      expect:
        command: /bin/bash -c "/usr/sbin/realm -v join --user={{ lookup('env','AZURE_AD_USER') }}@{{ active_directory_domain }} --computer-ou={{ active_directory_cent7_ou }} {{ active_directory_domain }} --install=/"
        responses:
          Password for *: "{{ lookup('env','AZURE_PASSWORD') }}"
      notify:
        - restart sshd
      when: (realmd_bound is failed and dist == "centos7")


    - name: Join system to AD and put the computer object in the Linux Servers OU (Ubuntu)
      expect:
        command: /bin/bash -c "/usr/sbin/realm -v join --user={{ lookup('env','AZURE_AD_USER') }}@{{ active_directory_domain }} --computer-ou={{ active_directory_ubuntu_ou }} {{ active_directory_domain }} --install=/"
        responses:
          Password for *: "{{ lookup('env','AZURE_PASSWORD') }}"
      notify:
        - restart sshd
      when: (realmd_bound is failed and dist == "ubuntu")

    - name: Add SSSD Conf from Template (All Distros)
      template:
        src: templates/sssd/centos_ad.conf
        dest: /etc/sssd/sssd.conf
      notify:
        - restart sssd
        

    - name: Join system to AD and put the computer object in the Linux Servers OU (CentOS 6)
      expect:
        command: /bin/bash -c "/usr/sbin/adcli join --login-user={{ lookup('env','AZURE_AD_USER') }} --domain-ou={{ active_directory_cent6_ou }}"
        responses:
          Password for *: "{{ lookup('env','AZURE_PASSWORD') }}"
      notify:
        - restart sshd
      when: dist == "centos6"
      
      
    - name: Disable LDAP auth using Authconfig (CentOS)
      command: authconfig --disableldapauth --disableldap --updateall
      when: ansible_distribution == 'CentOS'


  handlers:
    - name: restart sssd
      service:
        name: sssd
        state: restarted
    - name: restart sshd
      service:
        name: sshd
        state: restarted
      ignore_errors: true
